ARDUINO_DIR = /usr/share/arduino
ARDUINO_CORE_PATH = /usr/share/arduino/hardware/arduino/cores/arduino
#TARGET = StandardFirmata         # The same as your ino file name 
BOARD_TAG    = mega2560           # can also be mega2560
ARDUINO_PORT = /dev/ttyACM0  # be sure to change this to the port used by your board
MONITOR_PORT = /dev/ttyACM0
ISP_PORT = /dev/ttyACM0
ARDMK_DIR = /usr/share/arduino
#
USER_LIB_PATH = /home/pi/restart/headunit/arduino/libraries
ARDUINO_LIBS =  SoftwareSerial SoftwareSerial/include Firmata Firmata/utility Wire Servo
ARDUINO_DIR  = /usr/share/arduino
AVR_TOOLS_PATH = /usr/share/arduino/hardware/tools/avr/bin
AVR_DUDE = /usr/share/arduino/hardware/tools/avrdude
AVRDUDE_ARD_PROGRAMMER = wiring
BOARD_TXT = /usr/share/arduino/hardware/arduino/boards.txt
AVRDUDE_CONF = /usr/share/arduino/hardware/tools/avrdude.conf
#ARCHITECTURE = avr
BOOTLOADER_PARENT = /usr/share/arduino/hardware/arduino/bootloaders/stk500v2
# BOOTLOADER_PARENT = /usr/share/arduino/hardware/arduino/bootloaders
# ARDUINO_PLATFORM_LIB_PATH = /usr/share/arduino/hardware/arduino/avr/libraries
ARDUINO_VAR_PATH = /usr/share/arduino/hardware/arduino/variants
include /usr/share/arduino/Arduino.mk
